### ISSUE TITLE
Compatibility with mkdocstrings-python for cross references?

### ISSUE THREAD

**Issue by afuetterer** [KyleKing/mdformat-mkdocs#19]
Hi there,

I am a new user of mdformat and this plugin.

If this is the wrong place to report, please ignore and close the issue.

I use mkdocs and mkdocstrings-python for documentation. There I use cross references like `[Object][package.module.object]` or even `[package.module.object][]`, which according to markdown, are not valid links.  So the brackets get escaped to 

`\[Object\]\[package.module.object\]` and `\[package.module.object\]\[\]`

This was actually already reported at mdformat's issue tracker: https://github.com/executablebooks/mdformat/issues/112#issuecomment-1604024721

But maybe this is the better place to add compatibility with mkdocstrings-python? I think mkdocs and mkdocstrings-python is a common combination for docs.

What do you think?

**Comment by KyleKing** [comment]
Thanks for trying out `mdformat-mkdocs`!

That seems like a good feature to add here and I'll go ahead and implement after work.

I believe I had mdformat working for link references when the reference was defined, but my guess is that mkdocstrings is generating those references dynamically, which is why the brackets are being escaped, but that's just an initial guess.

**Comment by afuetterer** [comment]
Thanks.

So far I really enjoy mdformat and mdformat-mkdocs. The only thing that is bugging me is the cross references.

**Comment by KyleKing** [comment]
Okay, so reference links are handled by `mdformat` because they are defined in CommonMark. This is the relevant logic:

- Rule: https://github.com/executablebooks/markdown-it-py/blob/1064835b30325e857252f5b67b34e622261723ca/markdown_it/rules_block/reference.py#L25-L95
- Renderer: https://github.com/executablebooks/mdformat/blob/782cb22f294bc4ce48368ee173de4837fc208ecf/src/mdformat/renderer/_context.py#L235-L269
- Docs: https://github.com/executablebooks/mdformat/blob/782cb22f294bc4ce48368ee173de4837fc208ecf/docs/users/style.md?plain=1#L136-L157

The problem is that there is no detected definition for the provided label, which is why they are escaped: https://github.com/executablebooks/markdown-it-py/blob/1064835b30325e857252f5b67b34e622261723ca/markdown_it/rules_inline/link.py#L115-L120

My plan is to offer a CLI flag to conditionally turn off this strict behavior (e.g. `mdformat --ignore-missing-references file.md`)

**Comment by KyleKing** [comment]
I've released v2.0.5 with potential fixes. Let me know if that works!

**Note**: you'll need to include `--ignore-missing-references` to turn off the link reference protections in `mdformat`

For use in `pre-commit`, you might have something like:

```yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies: ['mdformat-mkdocs[recommended]>=2.0.5']
        args: [--ignore-missing-references, --wrap=no]
```

**Comment by afuetterer** [comment]
Sadly, it does not work for me. The brackets are still escaped.

I tried your pre-commit config, but it did not work. So I doubted my pre-commit set-up. In a fresh venv, I ran:

```console
$ pip install mdformat "mdformat-mkdocs[recommended]"
$ mdformat --version
mdformat 0.7.17 (mdformat_tables: 0.4.1, mdformat_footnote: 0.1.1, mdformat_admon: 2.0.2, mdformat_gfm: 0.3.6, mdformat_simple_breaks: 0.0.1, mdformat_mkdocs: 2.0.5, mdformat_frontmatter: 2.0.8,
mdformat_config: 0.1.3, mdformat_web: 0.1.0, mdformat_beautysh: 0.1.1, mdformat_ruff: 0.1.3)
```

I created a test file, `test.md`.

```console
$ more docs/test.md
- [package.module.object][]
- [Object][package.module.object]
```

Running the cli directly

```console
$ mdformat --ignore-missing-references docs/test.md
```

changes the file and escapes the brackets.

```console
$ more docs/test.md
- \[package.module.object\]\[\]
- \[Object\]\[package.module.object\]
```

Am I doing something wrong here?

**Comment by KyleKing** [comment]
Nope, you're doing everything right and I can confirm the issue. Given that the test suite passes (https://github.com/KyleKing/mdformat-mkdocs/commit/52cd118b9b4f7f3600a48194a87d0b09cf560f98), my guess is that the order of plugins is causing issues. I'll be away this weekend, but I'll have time next week to resolve this!

**Comment by KyleKing** [comment]
Figured it out, I had incorrectly dropped the plural `s` 😌 (https://github.com/KyleKing/mdformat-mkdocs/commit/3dc80a03f4572ca701ef7b55aa75f0484018dde9)

`2.0.6` should really work! Sorry for the late night error

**Comment by afuetterer** [comment]
Thank you very much. With 2.0.6 it works as described and fixes the issue. Feel free to close.
